import { readFileSync, writeFileSync } from 'node:fs';
const read = p => readFileSync(p, 'utf8');
const write = (p, s) => writeFileSync(p, s);
function edit(p, from, to) {const s=read(p);if(!s.includes(from))throw new Error('Missing patch in '+p);write(p,s.replace(from,to));}
const doc='src/components/documents/ProfessionalDocument.astro';
edit(doc, '  .record__heading h3,', '  .document-section--research h3,\n  .record__heading h3,');
edit(doc, '                              <p class="record__summary">{item.details[0]}</p>', '                              {document.id === "cv" && (\n                                <p class="record__summary">{item.details[0]}</p>\n                              )}');
edit(doc, '                                <p class="record__summary">{item.summary}</p>\n                                <p class="record__tools">', '                                <p class="record__summary">{item.summary}</p>\n                                {document.id === "cv" && item.outcome && (\n                                  <p class="record__summary">{item.outcome}</p>\n                                )}\n                                <p class="record__tools">');
edit(doc, '{item.remote ? "Remote · " : ""}', '{item.remote && item.location !== "Remote" ? "Remote · " : ""}');
edit(doc, '    min-height: 10.8mm;\n    padding: 1.7mm 0;\n    grid-template-columns: minmax(0, 1fr) 34mm;\n    align-items: start;\n    gap: 2mm;', '    min-height: 0;\n    padding: 1.7mm 0;\n    grid-template-columns: 1fr;\n    align-items: start;\n    gap: 0.5mm;');
edit(doc, '    font-size: 6.9pt;', '    font-size: 7.4pt;');
edit(doc, '    font-size: 6.1pt !important;\n    text-align: right;', '    font-size: 7pt !important;\n    text-align: left;');
edit(doc, '    padding: 4.7mm;', '    padding: 3mm;');
let s=read(doc);let a=s.indexOf('  .document-sheet--cv[data-page-number="3"] .document-sections {');let b=s.indexOf('  @media screen',a);if(a<0||b<0)throw new Error('CV style block missing');
write(doc,s.slice(0,a)+'  .document-sheet--cv .project-grid {\n    grid-template-columns: 1fr;\n  }\n\n'+s.slice(b));
const path='src/data/profile/document-manifest.json';const manifests=JSON.parse(read(path));const cv=manifests.find(x=>x.id==='cv');const sections=cv.pages.flatMap(p=>p.sections);const find=id=>sections.find(s=>s.id===id);
cv.pageCount=4;
cv.pages=[cv.pages[0], {number:2,sections:[find('cv-experience-continued'),find('cv-research'),find('cv-coursework')]}, {number:3,sections:[find('cv-projects'),find('cv-education')]}, {number:4,sections:[find('cv-professional-credentials'),find('cv-additional-learning'),find('cv-credential-history')]}];
write(path,JSON.stringify(manifests,null,2)+'\n');
const settingsPath='src/data/profile/site-settings.json';const settings=JSON.parse(read(settingsPath));settings[0].documents.cvPages=4;write(settingsPath,JSON.stringify(settings,null,2)+'\n');
edit('src/lib/content/schemas.ts','cvPages: z.literal(3)','cvPages: z.literal(4)');
edit('src/pages/documents/index.astro','Choose a concise two-page resume or a fuller three-page CV, each available under both professional name variants.','Choose a concise resume or the fuller CV, each available under both professional name variants.');
write('src/data/profile/routes.json',read('src/data/profile/routes.json').replaceAll('three-page','four-page'));
edit('scripts/build-documents.mjs','pdf.setKeywords([displayName, "data scientist", "data engineer", label]);','pdf.setKeywords([displayName, identity.headline, "governed AI", "data engineering", label]);');
edit('scripts/build-documents.mjs','      const canvasBox = canvas.getBoundingClientRect();','      const canvasBox = canvas.getBoundingClientRect();\n      const footer = canvas.querySelector(".document-footer");\n      const contentBottom = footer\n        ? footer.getBoundingClientRect().top - millimetresToPixels(2)\n        : canvasBox.bottom;');
edit('scripts/build-documents.mjs','        const header = section.querySelector(".document-section__header");','        if (sectionBox.bottom > contentBottom + 0.5) {\n          findings.push(\n            `Section ${section.getAttribute("data-document-section")} enters the reserved footer area on page ${pageIndex + 1}`,\n          );\n        }\n\n        const header = section.querySelector(".document-section__header");');
console.log('Applied readable document pagination and footer collision guard.');
